version: 2.1

orbs:
  # Required for feature specs.
  browser-tools: circleci/browser-tools@1.1

  # The orb version v0.7.3 until Solidus 3.4, which is the last version of
  # Solidus that v4 of `solidus_stripe` can reasonably support.
  solidusio_extensions: solidusio/extensions@0.7.3

executors:
  sqlite:
    description: Run specs with an SQLite
    docker:
      - image: cimg/ruby:3.0-browsers
        environment:
          RAILS_ENV: test
          DB: sqlite

jobs:
  run-specs-with-postgres:
    executor:
      name: solidusio_extensions/postgres
      ruby_version: "3.0"
    steps:
      - checkout
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current
  run-specs-with-mysql:
    executor:
      name: solidusio_extensions/mysql
      ruby_version: "3.0"
    steps:
      - checkout
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current
  run-specs-with-sqlite:
    executor: sqlite
    steps:
      - checkout
      - browser-tools/install-chrome
      - solidusio_extensions/run-tests-solidus-older
      - solidusio_extensions/run-tests-solidus-current

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
      - run-specs-with-sqlite
